// flow-typed signature: f64d4bd3449206dcdb8f6e191c04e85f
// flow-typed version: <<STUB>>/react-currency-formatter_v^1.1.0/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-currency-formatter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-currency-formatter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-currency-formatter/dist/react-currency-formatter.cjs' {
  declare module.exports: any;
}

declare module 'react-currency-formatter/dist/react-currency-formatter.esm' {
  declare module.exports: any;
}

declare module 'react-currency-formatter/dist/react-currency-formatter.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-currency-formatter/dist/react-currency-formatter.cjs.js' {
  declare module.exports: $Exports<'react-currency-formatter/dist/react-currency-formatter.cjs'>;
}
declare module 'react-currency-formatter/dist/react-currency-formatter.esm.js' {
  declare module.exports: $Exports<'react-currency-formatter/dist/react-currency-formatter.esm'>;
}
declare module 'react-currency-formatter/dist/react-currency-formatter.umd.js' {
  declare module.exports: $Exports<'react-currency-formatter/dist/react-currency-formatter.umd'>;
}
